# Generated by Django 3.1.7 on 2021-03-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_1', models.CharField(max_length=500)),
                ('slot_2', models.CharField(max_length=500)),
                ('slot_3', models.CharField(max_length=500)),
            ],
        ),
    ]
